# Variable to set the compiler
CC = g++

# Flags for compiling C++ files
CFLAGS = -Wall -O3 -g -std=c++0x -larmadillo

all: StatePrep

# Build rule for the executable file
StatePrep: StatePrep.cpp
	$(CC) $(CFLAGS) StatePrep.cpp -o StatePrep